spring.application.name=starter-demo

spring.datasource.url=jdbc:postgresql://localhost:5432/spartantutor
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=8218

spring.sql.init.mode=always